mysql:
  host: 127.0.0.1
  port: 3306
  database: "hyren"
  username: "root"
  password: ""

information:
  material: '397:3'
  head-texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDAxYWZlOTczYzU0ODJmZGM3MWU2YWExMDY5ODgzM2M3OWM0MzdmMjEzMDhlYTlhMWEwOTU3NDZlYzI3NGEwZiJ9fX0='
  display-name: '&eInformações'
  lore:
    - '&7Para colocar a sua loja aqui,'
    - '&7você tem de definir a sua'
    - ''
    - '&7localização com &f/loja setloc'
    - '&7no seu terreno.'
    - ''
    - '&7Todos os dias, você pode'
    - '&7avaliar uma loja dando-lhe'
    - '&fuma estrela§&!'
  slot: 49
  glow: false
stores:
  material: '397:3'
  display-name: '<ranked> &aLoja de <name>'
  lore:
    - '&7Faça compras na loja'
    - '&7deste jogador!'
    - ''
    - ' &fEstrelas: &7<stars>'
    - ' &fVisitantes: &7<visits>'
    - ''
    - '&fClique esquerdo: &7ir.'
    - '&fClique direito: &7dar estrela.'
  glow: false